import { MovieTitle, UserReview, Director } from "./src/types";

export const SEED_DIRECTORS: Director[] = [
  {
    id: "christopher-nolan",
    name: "Кристофер Нолан",
    originalName: "Christopher Nolan",
    yearsOfLife: "1970 – н.в. (55 лет)",
    photoUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=400&q=80",
    quote: "Я всегда пытаюсь дать зрителю субъективный кинематографический опыт, заставить его почувствовать себя внутри истории.",
    biography: "Кристофер Нолан — британский и американский кинорежиссёр, сценарист и продюсер. Один из самых кассовых режиссёров в истории. Известен нелинейными сюжетами, интеллектуальными блокбастерами и мастерской работой со временем. Нолан неоднократно номинировался на премии «Оскар», получив долгожданные статуэтки за фильм «Оппенгеймер».",
    country: "Великобритания, США",
    style: "Интеллектуальный блокбастер, нелинейный монтаж, практические спецэффекты, съемка на IMAX-пленку.",
    keyThemes: ["Время и память", "Субъективность реальности", "Жертвенность"],
    awards: ["Оскар за Лучшую режиссуру (Оппенгеймер)", "Золотой глобус", "BAFTA"]
  },
  {
    id: "aleksey-balabanov",
    name: "Алексей Балабанов",
    originalName: "Aleksey Balabanov",
    yearsOfLife: "1959 – 2013 (Почил в возрасте 54 лет)",
    photoUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80",
    quote: "Я хочу сказать, что кино — это не только искусство. Кино — это жизнь, показанная просто.",
    biography: "Алексей Октябринович Балабанов — культовый российский кинорежиссёр, сценарист и продюсер. Создатель легендарной дилогии «Брат», лент «Жмурки», «Война». Его творчество отличается глубоким реализмом, беспощадной честностью, тонким чувством народного духа и использованием рок-музыки.",
    country: "Россия",
    style: "Черный юмор, бытовой экзистенциализм, провинциальный реализм, русский рок как элемент повествования.",
    keyThemes: ["Поиск внутренней правды", "Кризис маскулинности", "Сиротство и эхо войн"],
    awards: ["Специальный приз жюри «Кинотавра»", "Премия «Ника»", "Премия «Золотой овен»"]
  },
  {
    id: "quentin-tarantino",
    name: "Квентин Тарантино",
    originalName: "Quentin Tarantino",
    yearsOfLife: "1963 – н.в. (63 года)",
    photoUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&q=80",
    quote: "Я не ходил в киношколу, я ходил в кино.",
    biography: "Квентин Джером Тарантино — американский режиссёр, сценарист и актёр. Мировую славу ему принес эпохальный фильм «Криминальное чтиво», взявший «Золотую пальмовую ветвь» в Каннах. Лауреат двух премий «Оскар» за лучшие оригинальные сценарии. Кинематограф Тарантино построен на цитировании любимой поп-культуры и спагетти-вестернов.",
    country: "США",
    style: "Длинные искрометные диалоги, эстетизация насилия, постмодернистская ирония, нелинейный монтаж.",
    keyThemes: ["Месть как мотиватор", "Криминальные кодексы чести", "Переосмысление истории"],
    awards: ["Золотая пальмовая ветвь Канн", "Два Оскара за Лучший сценарий", "Золотой глобус"]
  },
  {
    id: "leonid-gaidai",
    name: "Леонид Гайдай",
    originalName: "Leonid Gaidai",
    yearsOfLife: "1923 – 1993 (Почил в возрасте 70 лет)",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    quote: "Комедия — дело чрезвычайно серьезное. Смешить людей гораздо труднее, чем заставлять их плакать.",
    biography: "Леонид Иович Гайдай — выдающийся советский кинорежиссёр, сценарист, актёр, народный артист СССР. Величайший мастер советской эксцентрической и сатирической комедии. Создатель народных шедевров: «Кавказская пленница», «Бриллиантовая рука», «Иван Васильевич меняет профессию».",
    country: "СССР",
    style: "Эксцентрическая визуальная комедия, буффонада, яркие речевые штампы, музыкальные номера-хиты.",
    keyThemes: ["Маленький человек против системы", "Высмеивание мещанства", "Авантюризм"],
    awards: ["Народный артист СССР", "Государственная премия РСФСР"]
  },
  {
    id: "vince-gilligan",
    name: "Винс Гиллиган",
    originalName: "Vince Gilligan",
    yearsOfLife: "1967 – н.в. (59 лет)",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    quote: "У нас хорошим парням везет, а плохие несут наказание. Мне хотелось посмотреть, что будет с обычным человеком.",
    biography: "Джордж Винсент Гиллиган-младший — американский сценарист, режиссёр и продюсер. Создатель великих драматических сериалов «Во все тяжкие» (Breaking Bad) и «Лучше звоните Солу» (Better Call Saul). Написал новые правила золотого века телевидения.",
    country: "США",
    style: "Глубокий психологизм, символизм предметов, экстремальные ракурсы, медленное нагнетание драмы.",
    keyThemes: ["Моральная деградация", "Причинно-следственные связи грехов", "Гордыня и эгоизм"],
    awards: ["Многократный лауреат Эмми", "Премия Гильдии сценаристов США", "Премия Пибоди"]
  },
  {
    id: "tetsuro-araki",
    name: "Тэцуро Араки",
    originalName: "Tetsuro Araki",
    yearsOfLife: "1976 – н.в. (49 лет)",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    quote: "Анимация дает идеальную творческую свободу передать пафос и триумф человека.",
    biography: "Тэцуро Араки — японский режиссёр аниме, наиболее известный по работе на студиях Madhouse и Wit Studio. Поставил культовые тайтлы «Тетрадь смерти» и «Атака титанов». Режиссура славится динамикой, глубоким пафосом и эпической музыкой.",
    country: "Япония",
    style: "Высокий драматизм, скоростная динамика экшена, крупные планы, глубокие светотени.",
    keyThemes: ["Обреченное выживание человечества", "Дуализм добра и зла в борьбе умов", "Бунт против судьбы"],
    awards: ["Tokyo Anime Award за Лучшего режиссера", "Newtype Anime Awards"]
  },
  {
    id: "michael-bay",
    name: "Майкл Бэй",
    originalName: "Michael Bay",
    yearsOfLife: "1965 – н.в. (61 год)",
    photoUrl: "https://images.unsplash.com/photo-1481214110143-bc634afd196b?auto=format&fit=crop&w=400&q=80",
    quote: "Я снимаю фильмы для мальчишек-подростков. И извиняться за это не собираюсь.",
    biography: "Майкл Бенджамин Бэй — американский режиссер и продюсер экшен-фильмов. Создатель франшизы «Трансформеры», а также научно-фантастической драмы «Армагеддон». Его визитная карточка — визуальный стиль 'Bayhem' с обилием взрывов и масштабными планами.",
    country: "США",
    style: "Bayhem, сверхдинамичный клиповый монтаж, красивый свет на закате, взрывоопасные спецэффекты.",
    keyThemes: ["Спасение Земли в последний момент", "Военный патриотизм", "Технологии будущего"],
    awards: ["MTV Movie Awards", "Премия Сатурн за лучшую режиссуру (Армагеддон)"]
  },
  {
    id: "hayao-miyazaki",
    name: "Хаяо Миядзаки",
    originalName: "Hayao Miyazaki",
    yearsOfLife: "1941 – н.в. (85 лет)",
    photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    quote: "Я верю, что детская душа унаследовала историческую память. Наша задача — разбудить ее доброй сказкой.",
    biography: "Хаяо Миядзаки — легендарный японский аниматор, режиссёр, сценарист и основатель Studio Ghibli. Человек, открывший миру красоту рисованной аниме-эстетики. Обладатель двух премий «Оскар» («Унесённые призраками», «Мальчик и цапля»).",
    country: "Япония",
    style: "Ручная рисовка фонов, детальные летающие машины, созерцательные беззвучные паузы.",
    keyThemes: ["Экология и природа", "Эхо и ужасы войны", "Взросление и обретение дружбы"],
    awards: ["Два Оскара за Лучший анимационный фильм", "Венецианский Золотой Лев за вклад в кино", "Почётный Оскар"]
  },
  {
    id: "denis-villeneuve",
    name: "Дени Вильнёв",
    originalName: "Denis Villeneuve",
    yearsOfLife: "1967 – н.в. (58 лет)",
    photoUrl: "https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=400&q=80",
    quote: "Для меня кино — гипнотическое визуальное путешествие, где звук и картинка захватывают твое подсознание сильнее слов.",
    biography: "Дени Вильнёв — канадский кинорежиссёр и сценарист, один из главных визионеров современной научной фантастики. Обладатель мирового признания за картины «Прибытие», киберпанк «Бегущий по лезвию 2049» и грандиозный эпос «Дюна».",
    country: "Канада, США",
    style: "Монументальный геометрия кадра, медленный вибрирующий повествовательный ритм, глубокие басы.",
    keyThemes: ["Фатализм судьбы", "Трудности первого контакта с неизведанным", "Психологические травмы и месть"],
    awards: ["Номинации на Оскар", "Премия Ассоциации кинокритиков за лучшую режиссуру (Дюна)"]
  }
];

export const SEED_MOVIES: MovieTitle[] = [
  {
    id: "interstellar",
    slug: "interstellar",
    title: "Интерстеллар",
    originalTitle: "Interstellar",
    type: "movie",
    year: 2014,
    releaseDate: "2014-11-06",
    genres: ["Фантастика", "Драма", "Приключения"],
    duration: "169 мин",
    country: "США, Великобритания",
    director: "Кристофер Нолан",
    cast: ["Мэттью Макконахи", "Энн Хэтэуэй", "Джессика Честейн", "Майкл Кейн"],
    overview: "Группа космонавтов отправляется сквозь wormhole в отдаленные уголки космоса ради поиска нового дома для угасающего человечества.",
    backdropUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    ratingsAverageBreakdown: { story: 9.2, acting: 8.9, visuals: 9.8, sound: 9.9, genreMatch: 9.5 },
    ratingAverage: 91.4,
    ratingsCount: 423
  },
  {
    id: "inception",
    slug: "inception",
    title: "Начало",
    originalTitle: "Inception",
    type: "movie",
    year: 2010,
    releaseDate: "2010-07-22",
    genres: ["Фантастика", "Боевик", "Триллер"],
    duration: "148 мин",
    country: "США, Великобритания",
    director: "Кристофер Нолан",
    cast: ["Леонардо ДиКаприо", "Джозеф Гордон-Левитт", "Эллиот Пейдж", "Том Харди"],
    overview: "Профессиональный вор Кобб крадет секреты из глубин подсознания во время сна. Ему выпадает шанс вернуть жизнь, внедрив идею.",
    backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    ratingsAverageBreakdown: { story: 9.5, acting: 9.2, visuals: 9.7, sound: 9.6, genreMatch: 9.8 },
    ratingAverage: 93.5,
    ratingsCount: 512
  },
  {
    id: "prestige",
    slug: "prestige",
    title: "Престиж",
    originalTitle: "The Prestige",
    type: "movie",
    year: 2006,
    releaseDate: "2006-10-20",
    genres: ["Драма", "Триллер", "Фантастика"],
    duration: "130 мин",
    country: "США, Великобритания",
    director: "Кристофер Нолан",
    cast: ["Хью Джекман", "Кристиан Бэйл", "Скарлетт Йоханссон", "Майкл Кейн"],
    overview: "Противостояние двух иллюзионистов в Лондоне на рубеже веков перерастает в смертельную войну за секрет величайшего фокуса.",
    backdropUrl: "https://images.unsplash.com/photo-1510519138101-570d1dca3d66?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 9.1, acting: 9.0, visuals: 8.8, sound: 8.7, genreMatch: 9.3 },
    ratingAverage: 87.5,
    ratingsCount: 290
  },
  {
    id: "brother-1997",
    slug: "brother-1997",
    title: "Брат",
    originalTitle: "Brat",
    type: "movie",
    year: 1997,
    releaseDate: "1997-05-17",
    genres: ["Драма", "Криминал", "Боевик"],
    duration: "99 мин",
    franchise: "Брат",
    country: "Россия",
    director: "Алексей Балабанов",
    cast: ["Сергей Бодров мл.", "Виктор Сухоруков", "Светлана Письмиченко"],
    overview: "Данила Багров возвращается из армии и едет в Петербург к брату Виктору, который оказывается наемным убийцей.",
    backdropUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/v9S_6Yv8ZgU",
    ratingsAverageBreakdown: { story: 8.8, acting: 9.2, visuals: 8.5, sound: 9.8, genreMatch: 9.5 },
    ratingAverage: 87.7,
    ratingsCount: 310
  },
  {
    id: "brother-2-2000",
    slug: "brother-2-2000",
    title: "Брат 2",
    originalTitle: "Brat 2",
    type: "movie",
    year: 2000,
    releaseDate: "2000-05-11",
    genres: ["Драма", "Криминал", "Боевик"],
    duration: "127 min",
    franchise: "Брат",
    country: "Россия, США",
    director: "Алексей Балабанов",
    cast: ["Сергей Бодров мл.", "Виктор Сухоруков", "Сергей Маковецкий"],
    overview: "Данила Багров едет в Америку, чтобы защитить права погибшего друга-армейца, где наводит жесткий справедливый порядок.",
    backdropUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/5F2vA2098D0",
    ratingsAverageBreakdown: { story: 9.0, acting: 9.3, visuals: 8.9, sound: 9.9, genreMatch: 9.6 },
    ratingAverage: 91.5,
    ratingsCount: 310
  },
  {
    id: "zhmurki",
    slug: "zhmurki",
    title: "Жмурки",
    originalTitle: "Dead Man's Bluff",
    type: "movie",
    year: 2005,
    releaseDate: "2005-05-24",
    genres: ["Комедия", "Криминал"],
    duration: "111 мин",
    country: "Россия",
    director: "Алексей Балабанов",
    cast: ["Алексей Панин", "Дмитрий Дюжев", "Никита Михалков", "Сергей Маковецкий"],
    overview: "Мрачная и уморительная криминальная сатира Балабанова о бандитах из Нижнего Новгорода эпохи бурных 90-х.",
    backdropUrl: "https://images.unsplash.com/photo-1522083165195-342750297f46?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1599831086111-a8dc0e62c161?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 8.3, acting: 8.8, visuals: 8.0, sound: 8.4, genreMatch: 8.5 },
    ratingAverage: 82.5,
    ratingsCount: 195
  },
  {
    id: "pulp-fiction",
    slug: "pulp-fiction",
    title: "Криминальное чтиво",
    originalTitle: "Pulp Fiction",
    type: "movie",
    year: 1994,
    releaseDate: "1994-10-14",
    genres: ["Криминал", "Триллер", "Драма", "Комедия"],
    duration: "154 мин",
    country: "США",
    director: "Квентин Тарантино",
    cast: ["Джон Траволта", "Сэмюэл Л. Джексон", "Ума Турман", "Брюс Уиллис"],
    overview: "Культовая нелинейная история двоих киллеров из Лос-Анджелеса, их босса, его жены и боксера-неудачника.",
    backdropUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/s7EgWkyY_Hk",
    ratingsAverageBreakdown: { story: 9.3, acting: 9.6, visuals: 9.4, sound: 9.7, genreMatch: 9.8 },
    ratingAverage: 93.7,
    ratingsCount: 460
  },
  {
    id: "django-unchained",
    slug: "django-unchained",
    title: "Джанго освобождённый",
    originalTitle: "Django Unchained",
    type: "movie",
    year: 2012,
    releaseDate: "2012-12-25",
    genres: ["Вестерн", "Драма", "Боевик"],
    duration: "165 мин",
    country: "США",
    director: "Квентин Тарантино",
    cast: ["Джейми Фокс", "Кристоф Вальц", "Леонардо ДиКаприо", "Кэрри Вашингтон"],
    overview: "Освобожденный раб Джанго вместе с немецким охотником за головами отправляется спасать свою жену от жестокого плантатора.",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 9.0, acting: 9.6, visuals: 9.3, sound: 9.4, genreMatch: 9.5 },
    ratingAverage: 91.2,
    ratingsCount: 380
  },
  {
    id: "ivan-vasilievich",
    slug: "ivan-vasilievich",
    title: "Иван Васильевич меняет профессию",
    originalTitle: "Ivan Vasilievich menyaet professiyu",
    type: "movie",
    year: 1973,
    releaseDate: "1973-09-17",
    genres: ["Комедия", "Фантастика", "Приключения"],
    duration: "88 мин",
    country: "СССР",
    director: "Леонид Гайдай",
    cast: ["Юрий Яковлев", "Леонид Куравлёв", "Александр Демьяненко"],
    overview: "Изобретатель Александр Тимофеев строит машину времени и меняет местами царя Ивана Грозного и управдома Буншу.",
    backdropUrl: "https://images.unsplash.com/photo-1522083165195-342750297f46?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1599831086111-a8dc0e62c161?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/a5S6JgB8Y6E",
    ratingsAverageBreakdown: { story: 9.5, acting: 9.8, visuals: 8.7, sound: 9.6, genreMatch: 9.5 },
    ratingAverage: 90.9,
    ratingsCount: 220
  },
  {
    id: "operation-y",
    slug: "operation-y",
    title: "Операция «Ы» и другие приключения Шурика",
    originalTitle: "Operatsiya Y i drugie priklyucheniya Shurika",
    type: "movie",
    year: 1965,
    releaseDate: "1965-07-23",
    genres: ["Комедия", "Приключения"],
    duration: "95 мин",
    country: "СССР",
    director: "Леонид Гайдай",
    cast: ["Александр Демьяненко", "Наталья Селезнёва", "Юрий Никулин", "Георгий Вицин"],
    overview: "Три уморительные новеллы о приключениях вежливого и находчивого студента Шурика, борющегося с хулиганами и жуликами.",
    backdropUrl: "https://images.unsplash.com/photo-1522083165195-342750297f46?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1599831086111-a8dc0e62c161?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 9.4, acting: 9.7, visuals: 8.4, sound: 9.5, genreMatch: 9.6 },
    ratingAverage: 91.8,
    ratingsCount: 280
  },
  {
    id: "breaking-bad",
    slug: "breaking-bad",
    title: "Во все тяжкие",
    originalTitle: "Breaking Bad",
    type: "tv",
    year: 2008,
    releaseDate: "2008-01-20",
    genres: ["Драма", "Криминал", "Триллер"],
    duration: "49 мин / 62 эп.",
    seasons: 5,
    episodesCount: 62,
    episodeDuration: 49,
    isEnded: true,
    endDate: "2013-09-29",
    country: "США",
    director: "Винс Гиллиган",
    cast: ["Брайан Крэнстон", "Аарон Пол", "Анна Ганн", "Боб Оденкёрк"],
    overview: "Узнав о смертельном диагнозе, школьный учитель химии Уолтер Уайт начинает варить мет, вовлекая бывшего ученика.",
    backdropUrl: "https://images.unsplash.com/photo-1542382257-201b7fcf870b?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1601512492572-c2e6f9898239?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
    ratingsAverageBreakdown: { story: 9.8, acting: 9.9, visuals: 9.2, sound: 9.4, genreMatch: 9.7 },
    ratingAverage: 93.8,
    ratingsCount: 588
  },
  {
    id: "attack-on-titan",
    slug: "attack-on-titan",
    title: "Атака титанов",
    originalTitle: "Shingeki no Kyojin",
    type: "anime",
    year: 2013,
    releaseDate: "2013-04-07",
    genres: ["Аниме", "Экшен", "Фэнтези", "Драма"],
    duration: "24 мин / 87 эп.",
    seasons: 4,
    episodesCount: 87,
    episodeDuration: 24,
    isEnded: true,
    endDate: "2023-11-05",
    country: "Япония",
    director: "Тэцуро Араки",
    cast: ["Юки Кадзи", "Юи Исикава", "Марина Иноуэ"],
    overview: "Человечество ведет войну на выживание с гигантскими людоедами во главе с Эреном Йегером, давшим смертельную клятву.",
    backdropUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/LHtdkW5__98",
    ratingsAverageBreakdown: { story: 9.6, acting: 9.1, visuals: 9.4, sound: 9.7, genreMatch: 9.8 },
    ratingAverage: 93.2,
    ratingsCount: 512
  },
  {
    id: "spirited-away",
    slug: "spirited-away",
    title: "Унесённые призраками",
    originalTitle: "Sen to Chihiro no Kamikakushi",
    type: "anime",
    year: 2001,
    releaseDate: "2001-07-20",
    genres: ["Аниме", "Анимация", "Фэнтези", "Сказка"],
    duration: "125 мин",
    country: "Япония",
    director: "Хаяо Миядзаки",
    cast: ["Руми Хираги", "Мию Ирино", "Мари Нацуки"],
    overview: "Девочка Тихиро попадает в волшебный мир духов Юбабы, откуда она должна спасти своих превращенных в свиней родителей.",
    backdropUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 9.7, acting: 9.3, visuals: 9.8, sound: 9.7, genreMatch: 9.9 },
    ratingAverage: 94.8,
    ratingsCount: 410
  },
  {
    id: "dune",
    slug: "dune",
    title: "Дюна",
    originalTitle: "Dune",
    type: "movie",
    year: 2021,
    releaseDate: "2021-09-16",
    genres: ["Фантастика", "Драма", "Приключения"],
    duration: "155 мин",
    country: "США, Канада",
    director: "Дени Вильнёв",
    cast: ["Тимоти Шаламе", "Ребекка Фергюсон", "Оскар Айзек", "Зендея"],
    overview: "Наследие пустынной планеты Арракис, гигантские черви и смертельное противостояние Великих Домов за спайс.",
    backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 8.7, acting: 9.0, visuals: 9.8, sound: 9.4, genreMatch: 9.2 },
    ratingAverage: 88.5,
    ratingsCount: 395
  },
  {
    id: "transformers-2007",
    slug: "transformers-2007",
    title: "Трансформеры",
    originalTitle: "Transformers",
    type: "movie",
    year: 2007,
    releaseDate: "2007-07-03",
    genres: ["Фантастика", "Боевик", "Приключения"],
    duration: "144 мин",
    franchise: "Трансформеры",
    country: "США",
    director: "Майкл Бэй",
    cast: ["Шайа ЛаБаф", "Меган Фокс", "Джош Дюамель", "Хьюго Уивинг"],
    overview: "Противостояние Автоботов и Десептиконов докатывается до Земли, где заложником великой войны роботов становится обычный подросток.",
    backdropUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=600&q=80",
    trailerUrl: "https://www.youtube.com/embed/gAjgXlhV_is",
    ratingsAverageBreakdown: { story: 7.2, acting: 7.0, visuals: 9.4, sound: 9.1, genreMatch: 8.8 },
    ratingAverage: 76.5,
    ratingsCount: 150
  },
  {
    id: "the-matrix",
    slug: "the-matrix",
    title: "Матрица",
    originalTitle: "The Matrix",
    type: "movie",
    year: 1999,
    releaseDate: "1999-03-31",
    genres: ["Фантастика", "Боевик"],
    duration: "136 мин",
    country: "США",
    director: "Лана Вачовски, Лилли Вачовски",
    composer: "Дон Дэвис",
    cast: ["Киану Ривз", "Лоренс Фишбёрн", "Кэрри-Энн Мосс", "Хьюго Уивинг"],
    overview: "Жизнь Томаса Андерсона разделена на две части: днём он обычный программист, а ночью — хакер Нео. Но однажды он узнает страшную правду: всё, что его окружает — лишь виртуальная иллюзия, созданная машинами.",
    backdropUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 9.6, acting: 9.0, visuals: 9.7, sound: 9.5, genreMatch: 9.8 },
    ratingAverage: 94.3,
    ratingsCount: 460
  },
  {
    id: "the-dark-knight",
    slug: "the-dark-knight",
    title: "Тёмный рыцарь",
    originalTitle: "The Dark Knight",
    type: "movie",
    year: 2008,
    releaseDate: "2008-07-18",
    genres: ["Боевик", "Триллер", "Криминал", "Драма"],
    duration: "152 мин",
    country: "США, Великобритания",
    director: "Кристофер Нолан",
    composer: "Ханс Циммер",
    cast: ["Кристиан Бэйл", "Хит Леджер", "Аарон Экхарт", "Мэгги Джилленхол"],
    overview: "Бэтмен поднимает ставки в войне с криминалом. С помощью лейтенанта Джима Гордона и прокурора Харви Дента он намерен очистить улицы Готэма. Но в городе появляется новый гений преступного мира по кличке Джокер.",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 9.5, acting: 9.9, visuals: 9.4, sound: 9.7, genreMatch: 9.8 },
    ratingAverage: 95.8,
    ratingsCount: 580
  },
  {
    id: "lotr-fellowship",
    slug: "lotr-fellowship",
    title: "Властелин колец: Братство Кольца",
    originalTitle: "The Lord of the Rings: The Fellowship of the Ring",
    type: "movie",
    year: 2001,
    releaseDate: "2001-12-19",
    genres: ["Фэнтези", "Приключения", "Драма"],
    duration: "178 мин",
    country: "Новая Зеландия, США",
    director: "Питер Джексон",
    composer: "Говард Шор",
    cast: ["Элайджа Вуд", "Иэн Маккеллен", "Вигго Мортенсен", "Шон Бин"],
    overview: "Хоббит Фродо Бэггинс получает опасное поручение: отнести Кольцо Всевластья к Роковой горе в Мордоре, чтобы уничтожить его раз и навсегда. На пути его сопровождает Братство Кольца.",
    backdropUrl: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=1200&q=80",
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    ratingsAverageBreakdown: { story: 9.7, acting: 9.4, visuals: 9.6, sound: 9.8, genreMatch: 9.9 },
    ratingAverage: 96.2,
    ratingsCount: 520
  }
];

export const SEED_REVIEWS: UserReview[] = [
  {
    id: "rev1",
    titleId: "interstellar",
    titleSlug: "interstellar",
    titleName: "Интерстеллар",
    titleYear: 2014,
    titleType: "movie",
    titlePoster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    userId: "critic1",
    username: "kinoman_99",
    userDisplayName: "Александр Елисеев",
    userAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    ratings: { story: 8, acting: 9, visuals: 10, sound: 10, genreMatch: 10 },
    averageRating: 92.5,
    text: "Потрясающий монументальный шедевр Кристофера Нолана. Режиссерское исполнение и масштаб поражают воображение. Органная музыка Ханса Циммера идеально подчеркивает величие космоса. Фильм оставляет незабываемое послевкусие.",
    createdAt: "2026-05-20T14:32:00Z",
    likes: ["critic2", "critic3", "critic4"]
  },
  {
    id: "rev2",
    titleId: "brother-1997",
    titleSlug: "brother-1997",
    titleName: "Брат",
    titleYear: 1997,
    titleType: "movie",
    titlePoster: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80",
    userId: "critic2",
    username: "balabanov_fan",
    userDisplayName: "Мария Смирнова",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    ratings: { story: 9, acting: 9, visuals: 8, sound: 10, genreMatch: 10 },
    averageRating: 90.0,
    text: "Балабанов уловил мрачный дух эпохи 90-х как никто другой. Данила Багров стал истинным народным героем. Музыка группы 'Наутилус Помпилиус' — полноценное действующее лицо картины.",
    createdAt: "2026-05-25T11:15:00Z",
    likes: ["critic1", "critic10"]
  },
  {
    id: "rev3",
    titleId: "attack-on-titan",
    titleSlug: "attack-on-titan",
    titleName: "Атака титанов",
    titleYear: 2013,
    titleType: "anime",
    titlePoster: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    userId: "critic3",
    username: "otaku_review",
    userDisplayName: "Константин Ким",
    userAvatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=150&q=80",
    ratings: { story: 10, acting: 9, visuals: 9, sound: 10, genreMatch: 10 },
    averageRating: 95.0,
    text: "Историческое аниме, которое смогло выйти далеко за рамки своего жанра. Гениальная история Хадзимэ Исаямы, динамичный экшен Тэцуро Араки и потрясающая музыка Савано.",
    createdAt: "2026-05-27T18:00:00Z",
    likes: ["critic1", "critic2", "critic8"]
  },
  {
    id: "rev4",
    titleId: "pulp-fiction",
    titleSlug: "pulp-fiction",
    titleName: "Криминальное чтиво",
    titleYear: 1994,
    titleType: "movie",
    titlePoster: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80",
    userId: "critic4",
    username: "tarantino_kid",
    userDisplayName: "Артур Ларин",
    userAvatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=150&q=80",
    ratings: { story: 10, acting: 10, visuals: 9, sound: 10, genreMatch: 10 },
    averageRating: 96.0,
    text: "Творение Тарантино, изменившее кино навсегда! Эти сочные диалоги, черный юмор, сумасшедший саундтрек и блестящая игра Траволты и Джексона. Пересматриваю бесконечно.",
    createdAt: "2026-05-28T09:40:00Z",
    likes: ["critic1", "critic5", "critic7"]
  },
  {
    id: "rev5",
    titleId: "dune",
    titleSlug: "dune",
    titleName: "Дюна",
    titleYear: 2021,
    titleType: "movie",
    titlePoster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    userId: "critic6",
    username: "scifi_girl",
    userDisplayName: "Елена Рей",
    userAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
    ratings: { story: 8, acting: 9, visuals: 10, sound: 10, genreMatch: 9 },
    averageRating: 91.0,
    text: "Вильнёв превзошел сам себя! Настоящая аудиовизуальная симфония. Монументальные кадры, пески Арракиса, невероятный звук от Ханса Циммера заставляют вжиматься в кресло.",
    createdAt: "2026-05-28T12:10:00Z",
    likes: ["critic1", "critic5"]
  },
  {
    id: "rev6",
    titleId: "spirited-away",
    titleSlug: "spirited-away",
    titleName: "Унесённые призраками",
    titleYear: 2001,
    titleType: "anime",
    titlePoster: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80",
    userId: "critic8",
    username: "doroma_love",
    userDisplayName: "Ирина Цой",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    ratings: { story: 10, acting: 9, visuals: 10, sound: 10, genreMatch: 10 },
    averageRating: 95.5,
    text: "Волшебная жемчужина Хаяо Миядзаки. Невероятно глубокая, атмосферная и терапевтическая притча для всех возрастов. Музыка Хисаиси трогает до глубины души.",
    createdAt: "2026-05-29T10:30:00Z",
    likes: ["critic3", "critic5", "critic7"]
  }
];
